import { expect } from "chai";
import hre  from "hardhat";
const { ethers,networkHelpers } = await hre.network.connect();
const originalWrite = process.stdout.write;
(process.stdout as any).write = function (string: string, encoding: any, fd: any) {
  if (typeof string === 'string' && string.includes('passing')) {
    // Регулярният израз намира и изтрива текстове като (176ms), (2s) и т.н.
    const cleanString = string.replace(/\s*\(\d+(ms|s)\)/g, '');
    return originalWrite.apply(process.stdout, [cleanString, encoding, fd]);
  }
  return originalWrite.apply(process.stdout, [string, encoding, fd]);
};
describe("BankSystem", function () {
	let BankContract;
	let bank;
	let admin, client1, client2, employee1, manager1, hacker;
	let createTx, approveTx;
	// Numeric IDs (tree_index) automatically generated by MySQL during KYC
	const CLIENT_1_ID = 101n;
	const CLIENT_2_ID = 102n;
	const EMPLOYEE_1_ID = 501n;
	const MANAGER_1_ID = 901n;
	const RECEIVER_ID = 888n; // Numerical ID of the accounting recipient
		beforeEach(async function () {
			// Retrieve test accounts from the Hardhat virtual machine
			[admin, client1, client2, employee1, manager1, hacker] = await ethers.getSigners();
			// Compile and deploy the optimized contract
			BankContract = await ethers.getContractFactory("BankSystem");
			bank = await BankContract.deploy();
			await bank.waitForDeployment();
			// The administrator registers the hardware addresses in the smart contract structures
			await bank.connect(admin).registerClient(client1.address, CLIENT_1_ID);
			await bank.connect(admin).registerClient(client2.address, CLIENT_2_ID);
			await bank.connect(admin).registerEmployee(employee1.address, EMPLOYEE_1_ID);
			await bank.connect(admin).registerManager(manager1.address, MANAGER_1_ID);
		});
		describe("1. Transaction Lifecycle and GDPR Compliance", function () {
			it("Customer creates a transaction - access control test", async function () {
				const transferAmount = ethers.parseEther("2.5"); // 2.5 ETH
				console.time("Method Execution Time");
				// STEP 1: Client 1 initiates a payment. The blockchain itself extracts its structure via msg.sender
				const createTx2 = bank.connect(client1).createTransfer(RECEIVER_ID, { value: transferAmount });
				console.timeEnd("Method Execution Time");
				// SCIENTIFIC AUDIT: We check that the creation log does NOT contain hardware addresses (GDPR)
				await expect(createTx2)
				.to.emit(bank, "TransferCreated")
				.withArgs(1, CLIENT_1_ID, transferAmount, RECEIVER_ID);
			});
			it("Employee approves a translation - acceess control test", async function () {
				// STEP 2: Employee 1 approves transaction #1
				console.time("Method Execution Time");
				const approveTx = await bank.connect(employee1).approveTransfer(1);
				console.timeEnd("Method Execution Time");
				// SCIENTIFIC AUDIT: The status change log contains only anonymous numbers for the audit log
				const currentTimestamp = await ethers.provider.getBlock("latest").then(b => b.timestamp);
				expect(approveTx)
				.to.emit(bank, "TransferStatusUpdated")
				.withArgs(1, EMPLOYEE_1_ID, 1, /* Status.Executed */ currentTimestamp);
			});
		});
		describe("2. Attacks simulation", function () {
			it("A hacker receives an immediate rejection - access control test", async function () {
				const transferAmount = ethers.parseEther("1.0");
				const createTx2 = await bank.connect(client1).createTransfer(RECEIVER_ID, { value: transferAmount });
				await expect(createTx2)
				.to.emit(bank, "TransferCreated")
				.withArgs(1, CLIENT_1_ID, transferAmount, RECEIVER_ID);
				console.time("Method Execution Time");
				//The hacker tries to call the function
				expect(bank.connect(hacker).approveTransfer(1))
				.to.be.revertedWith("Rejection: Inactive employee!");
				console.timeEnd("Method Execution Time");
			});
			it("Fired employee rejected to approve - access control test", async function () {
				// 1. The IT Administrator changes the status of employee1's device to false
				const deactivateTx = await bank.connect(admin).setEmployeeActiveStatus(employee1.address, false);
				const currentTimestamp = await ethers.provider.getBlock("latest").then(b => b.timestamp);
				// Check the audit log for deactivation
				await expect(deactivateTx)
				.to.emit(bank, "RoleStatusChanged")
				.withArgs(EMPLOYEE_1_ID, "Employee", false, currentTimestamp);
				// 2. We make sure that the value in the chain structure has been changed
				const isActiveEmployee = await bank.isActiveEmployees(employee1.address);
				expect(isActiveEmployee).to.be.false;
				console.time("Method Execution Time");
				// 3. Former employee tries to approve a transaction directly in Arbitrum Orbit – EVM throws him out
				expect(bank.connect(employee1).approveTransfer(1))
				.to.be.revertedWith("Rejection: Inactive employee!");
				console.timeEnd("Method Execution Time");
			});
			it("Client 2 is forbidden to read the data of Client 1 - access control test", async function () {
				// Client 2 is trying to read the details of transfer #1 from his phone
				const transferAmount = ethers.parseEther("1.0");
				const createTx2 = await bank.connect(client1).createTransfer(RECEIVER_ID, { value: transferAmount });
				await expect(createTx2)
				.to.emit(bank, "TransferCreated")
				.withArgs(1, CLIENT_1_ID, transferAmount, RECEIVER_ID);
				// Since the ID in his structure (102) does not match the clientID of the transfer (101), the chain check is blocked
				console.time("Method Execution Time");
				expect(bank.connect(client2).getTransferDetails(1))
				.to.be.revertedWith("Cancellation: Insufficient rights to view transaction data!");
				console.timeEnd("Method Execution Time");
			});
		});
	});